# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=255)),
                ('a_info', models.CharField(max_length=300)),
                ('a_content', models.TextField()),
                ('a_img', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('a_addtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('a_updatetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-a_addtime'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('cls_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255)),
                ('t_info', models.CharField(max_length=300)),
                ('t_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Tag'),
        ),
    ]
