# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签'},
        ),
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_info',
            field=models.CharField(max_length=300, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_info',
            field=models.CharField(max_length=300, verbose_name='标签描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_name',
            field=models.CharField(max_length=255, verbose_name='标签名'),
        ),
        migrations.AlterModelTable(
            name='art',
            table='t_art',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='t_tag',
        ),
    ]
