# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20180531_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_img',
            field=models.ImageField(blank=True, null=True, upload_to='arts_ups/%Y/%m/%d'),
        ),
    ]
